#!/bin/sh
# firewall rules to run on system startup
WAN_IFACE="WAN"
DMZ_IFACE="DMZ"
lan_IFACE="lan"
case "$1" in
	start)
		echo "Starting FW"
		echo "1" > /proc/sys/net/ipv4/ip_forward
		iptables -t nat -F
		iptables -F INPUT
		iptables -F OUTPUT
		iptables -F FORWARD
		iptables -P INPUT DROP
		iptables -P OUTPUT DROP
		iptables -P FORWARD DROP
		iptables -A FORWARD -o $WAN_IFACE -j ACCEPT
		iptables -A FORWARD -i $lan_IFACE -o $DMZ_IFACE -j ACCEPT
		iptables -A FORWARD -i $lan_IFACE -o $WAN_IFACE -j ACCEPT
		iptables -A FORWARD -i $DMZ_IFACE -o $lan_IFACE -p icmp -j ACCEPT
		iptables -A FORWARD -i $DMZ_IFACE -o $WAN_IFACE -p tcp --dport 80 -j ACCEPT
		iptables -A FORWARD -i $DMZ_IFACE -o $WAN_IFACE -p tcp --dport 443 -j ACCEPT
		iptables -A FORWARD -i $DMZ_IFACE -o $WAN_IFACE -p icmp -j ACCEPT
		iptables -A FORWARD -i $DMZ_IFACE -o $WAN_IFACE -p udp --dport 53 -j ACCEPT
		iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
		iptables -A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
		iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
		iptables -t nat -A POSTROUTING -o $WAN_IFACE -j MASQUERADE
		iptables -A INPUT -i $DMZ_IFACE -p tcp --dport 2222 -j ACCEPT
		iptables -A OUTPUT -o $WAN_IFACE -p udp --dport 53 -j ACCEPT
		iptables -A OUTPUT -o $WAN_IFACE -p tcp --dport 80 -j ACCEPT
		iptables -A OUTPUT -o $WAN_IFACE -p tcp --dport 443 -j ACCEPT
		iptables -A INPUT -i $lan_IFACE -p tcp --dport 2222 -j ACCEPT
		iptables -t nat -A PREROUTING -i $WAN_IFACE -p tcp --dport 22 -j DNAT --to-destination 172.20.107.100:22
		iptables -t nat -A PREROUTING -i $WAN_IFACE -p udp --dport 53 -j DNAT --to-destination 172.20.107.100:53
		iptables -t nat -A PREROUTING -i $WAN_IFACE -p tcp --dport 53 -j DNAT --to-destination 172.20.107.100:53
		iptables -A FORWARD -p tcp -i $WAN_IFACE -d 172.20.107.100 --dport 22 -j ACCEPT
		iptables -A FORWARD -p tcp -i $WAN_IFACE -d 172.20.107.100 --dport 53 -j ACCEPT
		iptables -A FORWARD -p udp -i $WAN_IFACE -d 172.20.107.100 --dport 53 -j ACCEPT
		;;
	stop)
		echo "Stopping FW"
                iptables -t nat -F
                iptables -F INPUT
                iptables -F OUTPUT
                iptables -F FORWARD
		;;
	restart|reload)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac
exit 0
